# Generated by Django 3.1.3 on 2020-11-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('friendly_name', models.CharField(blank=True, max_length=99, null=True)),
                ('genre', models.CharField(max_length=99)),
                ('episodes_count', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=999, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('video_url', models.URLField(max_length=999)),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.series')),
            ],
        ),
    ]
