# Generated by Django 3.1.3 on 2020-11-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201124_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='serie',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
