# Generated by Django 3.1.3 on 2020-12-14 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('price', models.IntegerField(default=10)),
                ('subscription_type', models.CharField(choices=[('free', 'free'), ('premium', 'premium')], default='free', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
