# Generated by Django 3.1.3 on 2020-12-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premium', '0002_auto_20201216_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=69)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=69, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='user_subscription',
            name='date_of_last_payment',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_subscription',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
