# Generated by Django 3.1.3 on 2020-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_auto_20201227_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subscription',
            name='premium',
        ),
        migrations.AddField(
            model_name='user_subscription',
            name='premium_until',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
